# Generated by Django 3.2.6 on 2021-08-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('idx', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=15)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('agreement_information_collection', models.BooleanField()),
                ('agreement_sharing_collected_information', models.BooleanField()),
                ('agreement_marketing', models.BooleanField()),
            ],
            options={
                'db_table': 'customer_information',
            },
        ),
        migrations.CreateModel(
            name='MovingCompany',
            fields=[
                ('idx', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ceo', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=1024, unique=True)),
                ('business_number', models.CharField(max_length=256, unique=True)),
                ('business_reg_date', models.DateTimeField()),
                ('number_of_employees', models.IntegerField()),
                ('number_of_vehicles', models.IntegerField()),
                ('reservation_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'moving_company',
            },
        ),
        migrations.CreateModel(
            name='MovingReservation',
            fields=[
                ('idx', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=15)),
                ('start_address', models.CharField(max_length=256)),
                ('start_floor', models.IntegerField()),
                ('end_address', models.CharField(max_length=256)),
                ('end_floor', models.IntegerField()),
                ('moving_date', models.DateTimeField()),
                ('is_storage', models.BooleanField(default=False)),
                ('agreement_information_collection', models.BooleanField()),
                ('agreement_sharing_collected_information', models.BooleanField()),
                ('agreement_marketing', models.BooleanField()),
            ],
            options={
                'db_table': 'moving_reservation',
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedbackLog',
            fields=[
                ('idx', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('move_type', models.IntegerField()),
                ('agreement_open_information', models.BooleanField()),
                ('satisfied_pro', models.IntegerField()),
                ('satisfied_price', models.IntegerField()),
                ('satisfied_kindness', models.IntegerField()),
                ('revisit', models.BooleanField()),
                ('payment', models.IntegerField()),
                ('moving_date', models.DateTimeField()),
                ('feedback_date', models.DateTimeField()),
                ('feedback_text', models.TextField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moving.movingcompany')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moving.customerinformation')),
            ],
            options={
                'db_table': 'customer_feedback_log',
            },
        ),
    ]
